[package]
name = "workflow-i18n"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/workflow-rs/workflow-i18n"
keywords = ["i18n","translation","language","internationalization"]
categories = ["internationalization"]
exclude = ["/.*", "/test"]
description = """
i18n layer for Workflow UX framework
"""

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
thiserror = "1.0.32"
ritehash = "0.2.0"
